### ISSUE TITLE
[FEATURE REQUEST] Single timing files

### ISSUE THREAD

**Issue by Lisek573** [PerryAsleep/GrooveAuthor#16]
**Single timing files**
When I'm working on charts that have only singular timing I would like to have option to just have singular sync. Most of my files have single timing setting on all charts. Some do have per chart, but usually it's like 3 first diffs have base timing and 2 last have different. I would like to have option to use singular timing and then if needed create split timing for a certain difficulty.

This also affects performance of nine or null as if all charts have their own separate timing data, even if it is exactly same, it ends with them being checked multiple times.

This also is problem with single difficulty files, like for example, currently required for dimocracy contest, as there is rule to have only file timing, not chart timing.
https://i.imgur.com/6629tMl.png

**Comment by PerryAsleep** [comment]
I should be able to add this without too much difficulty. GrooveAuthor by default always prefers chart timing because it is more permissive than song timing. The way this will probably end up working is a checkbox on the Song Properties that when checked will force the Timing Chart's timing data to be written as the song timing data and it will force no chart timing data to be written. I'll also add an option to the Options menu so that this preference can additionally persist outside of the custom data GrooveAuthor saves per song/chart since you also [requested the ability to omit that data when saving](https://github.com/PerryAsleep/GrooveAuthor/issues/17).

If you are interested in the reasoning behind preferring chart timing I have some notes about it [here](https://github.com/PerryAsleep/GrooveAuthor/blob/main/StepManiaEditor/docs/SongAndChartTiming.md).

Thank you for sharing the contest rules that you are working under. Based on the text it looks like the intent behind that restriction is that they only want one chart per file but files can have one chart while still using chart timing. That said I'd like for users of GrooveAuthor to be able to use it for whatever scenarios they'd like as long it isn't major work to support that, so I am still happy to add this feature.

Also generally speaking I consider GrooveAuthor to be a tool for making content for Stepmania or itgmania. If other applications have unexpected performance issues with some content it may be appropriate to file a bug with those projects. Though again, I am happy to support song timing so that should help you avoid the performance problems you are experiencing in nine-or-null.

I am not yet sure when this feature will land as I am working on some other features at the moment but I will follow up here when it is complete.

**Comment by PerryAsleep** [comment]
In https://github.com/PerryAsleep/GrooveAuthor/commit/5d45e1aa9ada5d22174de893aa3524648f7e35db there is now a checkbox for forcing only song-level timing and omitting all chart-level timing when saving. This is available in [v0.2.3](https://github.com/PerryAsleep/GrooveAuthor/releases/tag/v0.2.3). This option can be found under `File` > `Advanced Save Options` > `Remove Chart Timing`.
