### ISSUE TITLE
Autogen is Limited to Dance Single and Dance Double

### ISSUE THREAD

**Issue by PCBoyGames** [PerryAsleep/GrooveAuthor#2]
When attempting to autogen styles that aren't Dance Single or Dance Doubles, the log outputs true of `if (!Editor.GetStepGraph(ChartType, out var outputStepGraph) || outputStepGraph == null)` in ActionAutoGenerateCharts (Line 92). I compiled the source and additionally logged the line numbers that make this output possible to verify that from a Dance Single, the destination Dance Solo has no StepGraph loaded.
![Screenshot 2024-01-29 154937](https://github.com/PerryAsleep/GrooveAuthor/assets/29846858/6e4ce22e-d83b-4d3e-b9db-a9b407fb3f68)

**Comment by PerryAsleep** [comment]
Hello! Thanks for your interest and effort debugging this.

Currently by default StepGraphs are only loaded for `dance-single` and `dance-double`. You can specify more in the options. Go to View > Options, then select additional types from the Startup Step Graphs list. If you select Dance Solo from that list, then restart, you will be able to autogen Solo charts.

So while it is possible, this is not very intuitive. I've been meaning to improve this. I at least want to add some more meaningful feedback about why certain actions can't be taken when StepGraphs aren't loaded. Though I am also considering just loading all StepGraphs at startup instead of just `dance-single` and `dance-double`. Some types like SMX Full and Pump Double are pretty big and I didn't know it was worth defaulting to loading those all the time if most users wouldn't need them. It's still something I'm thinking through.
