### ISSUE TITLE
[BUG] Saving with Ctrl+S sometimes switches you to Constant Time mode

### ISSUE THREAD

**Issue by compuerr** [PerryAsleep/GrooveAuthor#7]
**Bug Description**
Sometimes when using the keyboard shortcut Ctrl+S to save, you might get put into Constant Time scroll mode with a different Zoom factor.

**Steps to Reproduce**
1. Be in a mode that isn't Constant Time, I am in Variable mode when I notice this happen
2. Make an edit to the chart so it will let you save it
3. Press Ctrl+S to save

**Expected Behavior**
The scroll mode and zoom factor should not change when saving a file.

**Screenshots**

https://github.com/PerryAsleep/GrooveAuthor/assets/163092272/b213d065-a36f-4839-9dfa-68323d5795d1

**Version**
Version 0.1.0

**Log**
[GrooveAuthor 2024-03-23 19-07-34.log](https://github.com/PerryAsleep/GrooveAuthor/files/14734181/GrooveAuthor.2024-03-23.19-07-34.log)

**Comment by PerryAsleep** [comment]
Thank you for the bug report. `S` by itself changes the spacing mode, so it will toggle between constant time, constant row, and variable. `Ctrl+S` is save. The issue was holding `Ctrl+S` then releasing `Ctrl` before releasing `S` would unexpectedly trigger the action associated with `S`, and change the spacing mode.

This has been addressed in https://github.com/PerryAsleep/GrooveAuthor/commit/25c8229af4f9491adfc84a2758eaf5bde42588e5 and it should be available in the next release.
